<?php

namespace ContainerLHUqHw3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DIAq7uService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._dIAq7u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._dIAq7u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'JWTTokenManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
            'encoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'JWTTokenManager' => '?',
            'encoder' => '?',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
