<?php

namespace ContainerLHUqHw3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ItG2nuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ItG2nu_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ItG2nu_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'profilUserRepository' => ['privates', 'App\\Repository\\ProfilUserRepository', 'getProfilUserRepositoryService', true],
            'projetRepository' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'profilUserRepository' => 'App\\Repository\\ProfilUserRepository',
            'projetRepository' => 'App\\Repository\\ProjetRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
