<?php

namespace ContainerLHUqHw3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Describers_ConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.describers.config' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'Describer'.\DIRECTORY_SEPARATOR.'DescriberInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'Describer'.\DIRECTORY_SEPARATOR.'ExternalDocDescriber.php';

        return $container->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'My App', 'description' => 'This is an awesome app!', 'version' => '1.0.0'], 'components' => ['securitySchemes' => ['Bearer' => ['type' => 'http', 'scheme' => 'bearer', 'bearerFormat' => 'JWT']]], 'security' => [0 => ['Bearer' => []]], 'paths' => ['/api/login_check' => ['post' => ['tags' => [0 => 'Authentication'], 'summary' => 'Login into the api.', 'requestBody' => ['content' => ['application/json' => ['schema' => ['properties' => ['username' => ['type' => 'string'], 'password' => ['type' => 'string']], 'type' => 'object']]]], 'responses' => [200 => ['description' => 'OK', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['token' => ['type' => 'string'], 'refresh_token' => ['type' => 'string']]]]]], 401 => ['description' => 'Invalid credentials'], 400 => ['description' => 'Invalid JSON.']], 'security' => []]], '/api/users/countStat' => ['get' => ['tags' => [0 => 'Statistique-Users'], 'summary' => 'Nombre des utilisateurs total et nombre des utilisateur qui sont connectés actuellement', 'responses' => [200 => ['description' => 'OK', 'content' => ['application/json' => ['schema' => ['type' => 'object', 'properties' => ['title' => ['type' => 'string'], 'color' => ['type' => 'string'], 'subTitle' => ['type' => 'string'], 'imageIcon' => ['type' => 'string']]]]]], 401 => ['description' => 'Invalid credentials'], 400 => ['description' => 'Invalid JSON.']], 'security' => [0 => ['Bearer' => []]]]]]]);
    }
}
