<?php

namespace ContainerNJQuMvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YW19UUmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YW19UUm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YW19UUm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projetSectRepository' => ['privates', 'App\\Repository\\ProjetSectRepository', 'getProjetSectRepositoryService', true],
            'secteurRepository' => ['privates', 'App\\Repository\\SecteurRepository', 'getSecteurRepositoryService', true],
        ], [
            'projetSectRepository' => 'App\\Repository\\ProjetSectRepository',
            'secteurRepository' => 'App\\Repository\\SecteurRepository',
        ]);
    }
}
