gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000
    user_identity_field: email
    ttl_update: true
    firewall: api
    token_parameter_name: refreshToken


