<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pays extends \App\Entity\Pays implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'nomPays', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'drapeau', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'continent', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'departements', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'ongs', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'projets', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'projethists', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'DateCreat', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'UserCreat', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'DateModif', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'UserMotif'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'nomPays', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'drapeau', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'continent', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'departements', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'ongs', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'projets', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'projethists', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'DateCreat', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'UserCreat', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'DateModif', '' . "\0" . 'App\\Entity\\Pays' . "\0" . 'UserMotif'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pays $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPays', []);

        return parent::getNomPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPays(?string $nomPays): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPays', [$nomPays]);

        return parent::setNomPays($nomPays);
    }

    /**
     * {@inheritDoc}
     */
    public function getDrapeau(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDrapeau', []);

        return parent::getDrapeau();
    }

    /**
     * {@inheritDoc}
     */
    public function setDrapeau(?string $drapeau): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDrapeau', [$drapeau]);

        return parent::setDrapeau($drapeau);
    }

    /**
     * {@inheritDoc}
     */
    public function getContinent(): ?\App\Entity\Continent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContinent', []);

        return parent::getContinent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContinent(?\App\Entity\Continent $continent): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContinent', [$continent]);

        return parent::setContinent($continent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartements', []);

        return parent::getDepartements();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepartement(\App\Entity\Departement $departement): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepartement', [$departement]);

        return parent::addDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepartement(\App\Entity\Departement $departement): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepartement', [$departement]);

        return parent::removeDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function getOngs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOngs', []);

        return parent::getOngs();
    }

    /**
     * {@inheritDoc}
     */
    public function addOng(\App\Entity\Ong $ong): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOng', [$ong]);

        return parent::addOng($ong);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOng(\App\Entity\Ong $ong): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOng', [$ong]);

        return parent::removeOng($ong);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjets', []);

        return parent::getProjets();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjet(\App\Entity\Projet $projet): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjet', [$projet]);

        return parent::addProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProjet(\App\Entity\Projet $projet): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProjet', [$projet]);

        return parent::removeProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjethists(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjethists', []);

        return parent::getProjethists();
    }

    /**
     * {@inheritDoc}
     */
    public function addProjethist(\App\Entity\Projethist $projethist): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProjethist', [$projethist]);

        return parent::addProjethist($projethist);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProjethist(\App\Entity\Projethist $projethist): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProjethist', [$projethist]);

        return parent::removeProjethist($projethist);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreat', []);

        return parent::getDateCreat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreat($DateCreat): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreat', [$DateCreat]);

        parent::setDateCreat($DateCreat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', []);

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($DateModif): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', [$DateModif]);

        parent::setDateModif($DateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreat', []);

        return parent::getUserCreat();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreat(string $UserCreat): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreat', [$UserCreat]);

        return parent::setUserCreat($UserCreat);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserMotif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserMotif', []);

        return parent::getUserMotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserMotif(string $UserMotif): \App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserMotif', [$UserMotif]);

        return parent::setUserMotif($UserMotif);
    }

}
