<?php

namespace ContainerRUOIBJX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_DbHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'monolog.dbHandler' shared autowired service.
     *
     * @return \App\Utility\DbHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utility'.\DIRECTORY_SEPARATOR.'DbHandler.php';

        return $container->privates['monolog.dbHandler'] = new \App\Utility\DbHandler(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
