<?php

namespace ContainerBQTpVIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PSlx4t1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pSlx4t1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pSlx4t1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paramFetcher' => ['privates', '.errored.5YwEl.v', NULL, 'Cannot determine controller argument for "App\\Controller\\ApiController::getPlacesAction()": the $paramFetcher argument is type-hinted with the non-existent class or interface: "App\\Controller\\ParamFetcher". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.Rtkbxmd', NULL, 'Cannot determine controller argument for "App\\Controller\\ApiController::getPlacesAction()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'paramFetcher' => '?',
            'request' => '?',
        ]);
    }
}
