<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRUOIBJX\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRUOIBJX/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRUOIBJX.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRUOIBJX\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerRUOIBJX\App_KernelTestDebugContainer([
    'container.build_hash' => 'RUOIBJX',
    'container.build_id' => '328d669c',
    'container.build_time' => 1651181265,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRUOIBJX');
