<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrySlZP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrySlZP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrySlZP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrySlZP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLrySlZP\App_KernelDevDebugContainer([
    'container.build_hash' => 'LrySlZP',
    'container.build_id' => 'af4ac081',
    'container.build_time' => 1650572690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrySlZP');
