<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHUqHw3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHUqHw3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHUqHw3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHUqHw3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHUqHw3\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHUqHw3',
    'container.build_id' => 'bfc7eec0',
    'container.build_time' => 1652103471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHUqHw3');
